### Essential NumPy and Pandas Functions for Data Analysis

Let's look at practical code snippets that demonstrate the most useful NumPy and pandas methods for data analysis in Python. You can use these in a Jupyter notebook for experimentation and workflow mastery.

#### NumPy Basics for Data Analysis
Import NumPy:

In [6]:
import numpy as np

1. Creating Arrays

In [8]:
arr = np.array([1, 2, 3, 4])            # 1D array
matrix = np.array([[1, 2], [3, 4]])     # 2D array
zeros = np.zeros((2, 3))                # 2x3 array of zeros
ones = np.ones((2, 3))                  # 2x3 array of ones
rnd = np.random.rand(2, 3)              # 2x3 array of random floats

2. Array Shape, Reshape, Flatten

In [10]:
print(arr.shape)                # (4,)
reshaped = matrix.reshape((4, 1))   # Reshape to 4 rows, 1 column
flat = matrix.ravel()               # Flatten to 1D array

(4,)


3. Indexing and Slicing

In [12]:
print(matrix[0, 1])    # element at first row, second column
print(arr[1:3])        # slice elements 1 to 2

2
[2 3]


4. Basic Math Operations

In [14]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a + b)           # [11 22 33]
print(a - b)           # [ 9 18 27]
print(a * b)           # [10 40 90]
print(a / b)           # [10. 10. 10.]


[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


5. Aggregation and Stats

In [16]:
np.sum(arr)                 # 10
np.mean(arr)                # 2.5
np.std(arr)                 # Standard deviation
np.min(arr), np.max(arr)    # Min and max values

(1, 4)

6. Dot Product, Matrix Ops

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot = np.dot(a, b)          # 1*4 + 2*5 + 3*6 = 32
mat = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
matprod = np.matmul(mat, mat2) # Matrix multiplication

7. Logical and Filtering

In [20]:
arr[arr > 2]                # Returns [3, 4]
np.where(arr > 2)           # Indices where condition is true

(array([2, 3], dtype=int64),)

8. Random Sampling

In [22]:
np.random.randint(0, 100, size=5) # 5 random ints 0-99
np.random.choice([0, 1], size=10) # 10 random 0s or 1s

array([1, 1, 0, 0, 1, 1, 0, 0, 1, 1])

#### Pandas Basics for Data Analysis
Import pandas:

In [24]:
import pandas as pd

1. Creating DataFrames

In [26]:
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data) # Create DataFrame

2. Inspecting Data

In [28]:
df.head()                # First 5 rows
df.tail(3)                # Last 3 rows
df.info()                 # DataFrame info + datatypes
df.describe()             # Summary statistics

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes


A    B
count  3.0  3.0
mean   2.0  5.0
std    1.0  1.0
min    1.0  4.0
25%    1.5  4.5
50%    2.0  5.0
75%    2.5  5.5
max    3.0  6.0

3. Selecting Data

In [30]:
df['A']                   # Get column A
df.loc[0]                 # Row by label (index 0)
df.iloc[1:3]              # Rows 1-2 by position
df[df['A'] > 1]           # Filter rows where A > 1

A  B
1  2  5
2  3  6

4. Adding/Dropping Columns

In [32]:
df['C'] = df['A'] + df['B']     # Add new column
new_df = df.drop('B', axis=1)   # Drop column B

5. Missing Values & Types

In [34]:
df.isnull().sum()               # Missing values per column
df.fillna(0)                    # Replace NaNs with 0
df['A'] = df['A'].astype(float) # Change column type

6. Grouping and Aggregation

In [36]:
grouped = df.groupby('A').sum()   # Sum columns, grouped by values in A
df['A'].value_counts()            # Count unique values in A

A
1.0    1
2.0    1
3.0    1
Name: count, dtype: int64

7. Sorting

In [38]:
df.sort_values('B', ascending=False)  # Sort by column B

A  B  C
2  3.0  6  9
1  2.0  5  7
0  1.0  4  5

8. Reading/Writing Files

In [40]:
df.to_csv('mydata.csv') # Save to CSV
df = pd.read_csv('mydata.csv') # Load from CSV
df.head()

Unnamed: 0    A  B  C
0           0  1.0  4  5
1           1  2.0  5  7
2           2  3.0  6  9

9. Apply/Map Functions

In [42]:
df['A_squared'] = df['A'].apply(lambda x: x**2) # Apply to column
df['B_label'] = df['B'].map({4: 'Low', 5: 'Med', 6: 'High'}) # Map values
df.sample(3)

Unnamed: 0    A  B  C  A_squared B_label
1           1  2.0  5  7        4.0     Med
2           2  3.0  6  9        9.0    High
0           0  1.0  4  5        1.0     Low

### Task:

- Generated a Synthetic Dataset with columns of `age`, `salary`, `department`, `years_experience`, and `is_manager`.

In [45]:
np.random.seed(42) # For reproducibility
n_samples = 100 # Number of samples

data = {
    'age': np.random.randint(18, 60, size=n_samples),
    'salary': np.random.randint(30000, 120000, size=n_samples),
    'department': np.random.choice(['IT', 'HR', 'Finance', 'Marketing'], size=n_samples),
    'years_experience': np.round(np.random.normal(5, 2, size=n_samples), 1),
    'is_manager': np.random.choice([0, 1], size=n_samples)
}
df = pd.DataFrame(data)

Q1. View data structure

In [47]:
df

age  salary department  years_experience  is_manager
0    56   38392         IT              -0.8           0
1    46   60535  Marketing               3.4           1
2    32  108603         HR               5.0           1
3    25   82256         HR               4.2           1
4    38  119135         HR               4.1           1
..  ...     ...        ...               ...         ...
95   59   82662         IT               4.0           0
96   56   42688         HR               4.4           1
97   58   55342  Marketing               6.0           0
98   45   67157         HR              11.4           0
99   24   97863         HR               5.2           1

[100 rows x 5 columns]

Q2. Get DataFrame Info and Summary Stats

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   age               100 non-null    int32  
 1   salary            100 non-null    int32  
 2   department        100 non-null    object 
 3   years_experience  100 non-null    float64
 4   is_manager        100 non-null    int32  
dtypes: float64(1), int32(3), object(1)
memory usage: 2.9+ KB


In [50]:
df.dtypes

age                   int32
salary                int32
department           object
years_experience    float64
is_manager            int32
dtype: object

In [51]:
df.describe()

age         salary  years_experience  is_manager
count  100.000000     100.000000        100.000000  100.000000
mean    37.910000   77809.160000          4.823000    0.470000
std     12.219454   26058.643576          2.237822    0.501614
min     18.000000   30206.000000         -0.800000    0.000000
25%     26.750000   55141.000000          3.475000    0.000000
50%     38.000000   80932.000000          4.700000    0.000000
75%     46.250000   98107.250000          6.000000    1.000000
max     59.000000  119474.000000         11.400000    1.000000

Q3. Do Simple Numpy Operations

In [53]:
df['age'].max()

59

In [54]:
df['age'].min()

18

In [55]:
df['age'].mean()

37.91

In [56]:
df['age'].sum()

3791

In [93]:
df['age'].std()

12.21945377277767

Q4. Filtering and Indexing Rows

In [97]:
print( df[df['salary'] > 110000])

    age  salary department  years_experience  is_manager
4    38  119135         HR               4.1           1
8    28  114651  Marketing               5.8           1
17   41  112948  Marketing               6.7           1
20   19  117054  Marketing               6.7           0
21   38  117897    Finance               5.8           0
26   44  117939  Marketing               1.4           0
28   45  110356    Finance               5.7           1
35   26  111734         HR               3.8           0
76   42  113211         HR               8.6           0
79   32  119474  Marketing               4.3           1
82   24  115616         IT               9.3           1
89   34  117092    Finance               4.5           0
92   52  117455         IT               3.9           0


In [99]:
print(df[(df['department'] == 'Marketing') & (df['is_manager'] == 0)])

    age  salary department  years_experience  is_manager
7    40  109575  Marketing               6.9           0
11   53   54538  Marketing               5.3           0
18   47   36910  Marketing               7.6           0
20   19  117054  Marketing               6.7           0
26   44  117939  Marketing               1.4           0
27   59   48141  Marketing               4.5           0
32   54   63827  Marketing               9.2           0
33   24   85820  Marketing               8.1           0
39   42   94044  Marketing               1.8           0
52   57   51976  Marketing               3.5           0
54   19   53776  Marketing               3.9           0
59   35   85016  Marketing               7.4           0
61   51   88053  Marketing               5.3           0
64   31   33748  Marketing               6.9           0
71   38   84384  Marketing               5.8           0
74   41   69353  Marketing               3.3           0
75   43   92003  Marketing     

In [101]:
print(df[df['years_experience'] > 5])

    age  salary department  years_experience  is_manager
6    36  107373    Finance               6.7           1
7    40  109575  Marketing               6.9           0
8    28  114651  Marketing               5.8           1
10   41   40965         IT               9.5           1
11   53   54538  Marketing               5.3           0
12   57  100592    Finance               6.1           1
15   39   57266         IT               5.8           1
17   41  112948  Marketing               6.7           1
18   47   36910  Marketing               7.6           0
20   19  117054  Marketing               6.7           0
21   38  117897    Finance               5.8           0
24   39   80015    Finance               8.0           1
25   42   84268    Finance               5.8           0
28   45  110356    Finance               5.7           1
29   33  101910  Marketing               6.0           1
31   20   97214         IT               5.7           1
32   54   63827  Marketing     

Q5. Adding a Column

In [107]:
df['years_experience'] = df['years_experience'].clip(lower=0)

In [109]:
df['age_per_experience'] = (df['age'] / (df['years_experience'] + 1)).round(2)

In [111]:
df.head()

age  salary department  years_experience  is_manager  age_per_experience
0   56   38392         IT               0.0           0               56.00
1   46   60535  Marketing               3.4           1               10.45
2   32  108603         HR               5.0           1                5.33
3   25   82256         HR               4.2           1                4.81
4   38  119135         HR               4.1           1                7.45

Q6. Grouping and Aggregation

In [113]:
department_stats = df.groupby('department').agg(
    average_salary=('salary', 'mean'),
    average_age=('age', 'mean'),
    number_of_managers=('is_manager', 'sum')
)

In [115]:
print(department_stats)

            average_salary  average_age  number_of_managers
department                                                 
Finance       83124.708333    39.416667                  10
HR            73523.052632    37.157895                  10
IT            75825.476190    36.809524                  13
Marketing     77684.722222    37.944444                  14


In [119]:
department_stats['average_salary'] = department_stats['average_salary'].round(2)

In [121]:
print(department_stats)

            average_salary  average_age  number_of_managers
department                                                 
Finance           83124.71    39.416667                  10
HR                73523.05    37.157895                  10
IT                75825.48    36.809524                  13
Marketing         77684.72    37.944444                  14
